--- # Multiple Itmes
-  hosts: all
   tasks: 
   - name: "Install Common Libraries from CentOS mirror"
     yum: state=present name={{ item }}
     with_items:
      - sudo
      - vim
      - gcc
      - gcc-c++
      - autoconf
      - automake
      - libxml2-devel
      - unzip
      - createrepo
      - iotop
      - wget
      - tar
